# 测试抛出异常的方法 Testing Methods That Throw Exceptions
本篇记录了如何测试用来抛出异常的方法

### 测试抛出异常的方法时，有哪些断言标准？
很多情况下，我们需要断言抛出的异常是期望的异常。但断言抛出异常方法的时候是一个特殊情况。因为一旦满足异常条件，抛出的异常将直接中止测试。为了避免这种情况，断言异常时，应使用`委托`来进行。

### 如何使用委托断言抛出异常的情况？
在写断言方法时，将触发抛出异常值的语句写在委托中即可。如上篇的例子受测类`ErrorLogger`：
```c#
public class ErrorLogger
    {
        public string LastError { get; set; }

        public event EventHandler<Guid> ErrorLogged;    //定义事件，本篇忽略这个部分
        
        public void Log(string error)
        {
            if (String.IsNullOrWhiteSpace(error))   //检测error对象是否为空
                throw new ArgumentNullException();    //抛出异常
                
            LastError = error;
            
            // Write the log to a log
            // ...

            ErrorLogged?.Invoke(this, Guid.NewGuid());    //触发一个事件，本篇忽略这个部分
        }
    }
```
运用黑箱理论，不看执行细节，输入`error`有四种情况，即`error`为`null`、空字符串`""`、空白格`" "`和正常字符串四种。

其测试方法代码为：
