# 测试抛出异常的方法 Testing Methods That Throw Exceptions
本篇记录了如何测试用来抛出异常的方法

### 测试抛出异常的方法时，有哪些断言标准？
很多情况下，我们需要断言抛出的异常是期望的异常。但断言抛出异常方法的时候是一个特殊情况。因为一旦满足异常条件，抛出的异常将直接中止测试。为了避免这种情况，断言异常时，应使用`委托`来进行。

### 如何使用委托断言抛出异常的情况？
在写断言方法时，将触发抛出异常值的语句写在委托中即可。断言API为`Throws.ArgumentNullException`。
以上篇的例子受测类`ErrorLogger`为例：
```c#
public class ErrorLogger
    {
        public string LastError { get; set; }

        public event EventHandler<Guid> ErrorLogged;    //定义事件，本篇忽略这个部分
        
        public void Log(string error)
        {
            if (String.IsNullOrWhiteSpace(error))   //检测error对象是否为空
                throw new ArgumentNullException();    //抛出异常
                
            LastError = error;
            
            // Write the log to a log
            // ...

            ErrorLogged?.Invoke(this, Guid.NewGuid());    //触发一个事件，本篇忽略这个部分
        }
    }
```
运用黑箱理论，不看执行细节，输入`error`有四种情况，即`error`为`null`、空字符串`""`、空白格`" "`和正常字符串四种。

其完整测试方法代码为：
```c#
        [Test]
        [TestCase(null)]
        [TestCase("")]
        [TestCase(" ")]
        public void Log_WhenCalled_ThrowArgumentNullException(string error)
        {
            var logger = new ErrorLogger();

            Assert.That(() => logger.Log(error), Throws.ArgumentNullException);
        }
```
可以看到，当测试方法中抛出的异常时，省略掉`Act`步骤，因为执行触发异常会直接中断测试。

值得注意的是，本例中使用了`That()`方法中的第一个重载：
```c#
    public static void That(TestDelegate code, IResolveConstraint constraint);
```
即，第一个参数为委托代码，这里直接使用匿名表达式来执行方法；第二个参数为跟以前一样的`constraint`判定断言结果。

暂时想到这么多，最后更新2018/05/03
